"""Refresh commands/RESERVED_NAMES.txt from the installed Claude Code binary.

osiris's slash commands (commands/*.md, installed into ~/.claude/commands/ by
scripts/install_commands.sh) must never share a name with a Claude Code built-in command
or alias. Three did (/resume, /status, /stop, Claude Code 2.1.284) and a user typing one
got whichever side won the lookup, not a choice. RESERVED_NAMES.txt is the vendored list
the collision test (tests/test_command_names.py) and the installer both read; this script
regenerates its EXTRACTED section from the binary actually on this machine. The
SUPPLEMENT section (names the extraction misses, hand-maintained) is carried over as is.

Claude Code ships as one minified bundle, so the extraction is a set of regexes over the
binary's bytes, not an API. They cover the command-object shapes seen in 2.1.284:
  - name:"x",aliases:[...],description     (the original extraction)
  - type:"local|local-jsx|prompt",name:"x",aliases:[...]
  - name:"x",aliases:[...],type:"..."
  - aliases:[...],name:"x"                 (alias list before the name)
  - f({name:"x",aliases:[...]              (bundled skill registration)
Over-matching is harmless (a reserved name osiris never wanted is free); under-matching
is what the supplement is for. Run it after a Claude Code upgrade:

    uv run python scripts/refresh_reserved_names.py [--binary PATH] [--dry-run]
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESERVED_PATH = REPO_ROOT / "commands" / "RESERVED_NAMES.txt"

EXTRACTED_MARKER = "# --- extracted (regenerated by scripts/refresh_reserved_names.py) ---"
SUPPLEMENT_MARKER = "# --- supplement (hand-maintained, kept across refreshes) ---"

_NAME = r"([a-z][a-z0-9-]{1,30})"
_ALIASES = r"aliases:\[([^\]]*)\]"
_TYPE = r'type:"(?:local|local-jsx|prompt)"'
_PATTERNS = [
    re.compile(r'name:"([a-z][a-z-]{1,24})",(?:' + _ALIASES + r",)?description"),
    re.compile(_TYPE + r',name:"' + _NAME + r'"(?:,' + _ALIASES + r")?"),
    re.compile(r'name:"' + _NAME + r'"(?:,' + _ALIASES + r")?," + _TYPE),
    re.compile(_ALIASES + r',name:"' + _NAME + r'"'),
    re.compile(r'\b[A-Za-z$_]{1,3}\(\{name:"' + _NAME + r'"(?:,' + _ALIASES + r")?"),
]
_ALIAS_ITEM = re.compile(r'"([a-z][a-z0-9-]*)"')


def extract_names(blob: str) -> set[str]:
    """Every command name and alias the patterns above find in a decoded binary."""
    names: set[str] = set()
    for i, pattern in enumerate(_PATTERNS):
        for m in pattern.finditer(blob):
            if i == 3:  # aliases before the name
                aliases, name = m.group(1), m.group(2)
            else:
                name, aliases = m.group(1), m.group(2)
            names.add(name)
            if aliases:
                names.update(_ALIAS_ITEM.findall(aliases))
    return names


def read_reserved(path: Path = RESERVED_PATH) -> set[str]:
    """The reserved set as the installer and the test read it: first word of every
    non-blank, non-comment line."""
    if not path.is_file():
        return set()
    out: set[str] = set()
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.add(line.split()[0])
    return out


def _supplement(path: Path) -> list[str]:
    if not path.is_file():
        return []
    lines = path.read_text().splitlines()
    if SUPPLEMENT_MARKER not in lines:
        return []
    return lines[lines.index(SUPPLEMENT_MARKER) + 1:]


def _default_binary() -> Path | None:
    found = shutil.which("claude")
    return Path(os.path.realpath(found)) if found else None


def _version(binary: Path) -> str:
    try:
        out = subprocess.run([str(binary), "--version"], capture_output=True, text=True,
                             timeout=30, check=False).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return "unknown version"
    return out or "unknown version"


def render(names: set[str], version: str, supplement: list[str]) -> str:
    head = [
        "# Slash-command names osiris must never ship in commands/ or deploy/commands/:",
        "# Claude Code's built-in commands and their aliases. tests/test_command_names.py",
        "# fails on a collision; scripts/install_commands.sh refuses to install one.",
        f"# Extracted from: claude {version}",
        EXTRACTED_MARKER,
    ]
    body = sorted(names)
    tail = [SUPPLEMENT_MARKER, *supplement] if supplement else [SUPPLEMENT_MARKER]
    return "\n".join([*head, *body, *tail]).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--binary", type=Path, default=None,
                        help="Claude Code binary (default: realpath of `which claude`)")
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would change, write nothing")
    args = parser.parse_args(argv)
    binary = args.binary or _default_binary()
    if binary is None or not binary.is_file():
        print("refresh_reserved_names: no Claude Code binary found (pass --binary)",
              file=sys.stderr)
        return 1
    blob = binary.read_bytes().decode("latin-1")
    names = extract_names(blob)
    if not names:
        print(f"refresh_reserved_names: no command names found in {binary}; the bundle "
              "shape changed, update the patterns before trusting an empty list",
              file=sys.stderr)
        return 1
    before = read_reserved()
    text = render(names, _version(binary), _supplement(RESERVED_PATH))
    added = sorted(names - before)
    print(f"refresh_reserved_names: {len(names)} extracted from {binary}; "
          f"new vs current file: {', '.join(added) if added else 'none'}")
    if args.dry_run:
        return 0
    RESERVED_PATH.write_text(text)
    print(f"refresh_reserved_names: wrote {RESERVED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
